### ISSUE TITLE
Is fix-permissions.sh necessary?

### ISSUE THREAD

**Issue by kevinquillen** [alehkot/druphpet#21] opened 2015-03-18 20:27 UTC
This script fires every time I run vagrant up.

All of my files in the target directory are then set as 777 recursive - that isn't desirable to me. All of my Drupal files (not uploaded files, entire docroots) are now 777.

Is there a way to fix this or do we need this script?

**Comment by kevinquillen** [comment] 2015-03-18 20:48
I think what you would actually want to do here is something like (if this is indeed for the Drupal files folder):

```
shopt -s globstar
chmod g+s /var/www/path/to/sites/**/files
```

Haven't tried this so it might not work. The Drupal codebase should be mostly 775 and have normal permissions.

**Comment by kevinquillen** [comment] 2015-03-19 13:35
I commented this out for now and started a new vhost site and new Drupal install. No site effects that I can see... all permissions are correct. Definitely don't want 777.

**Comment by heyyoyo** [comment] 2015-03-22 10:45
Regarding file permissions there is an issue which has been fixed recently in puphpet:
https://github.com/puphpet/puphpet/issues/1356

**Comment by heyyoyo** [comment] 2015-03-22 10:47
And this one for NFS:
https://github.com/puphpet/puphpet/pull/1403

**Comment by alehkot** [comment] 2015-03-23 06:49
@heyyoyo I've just merged the latest changes from Puphpet. The issue should have gone.

**Comment by alehkot** [comment] 2015-03-23 06:50
Please reopen the ticket if the issue is reproducible.

**Closed by alehkot** 2015-03-23 06:49 UTC
